name:  Clean Workflow Runs
author: DevOps
description: Clean Workflow Runs

inputs:
  github-token:
    description: 'GitHub Token (github.token)'
    required: true
  repository:
    description: 'Repository (github.repository)'
    required: true  
  workflow:
    description: 'Workflow file name'
    required: true

runs:
  using: 'composite'
  steps:    
  - uses: actions/checkout@v4

  - env:
      GH_TOKEN: ${{ inputs.github-token }}
      REPOSITORY: ${{ inputs.repository }}
      WORKFLOW_NAME: ${{ inputs.workflow }}
    continue-on-error: true
    run: |
      echo "Getting all completed runs for workflow $WORKFLOW_NAME in $REPOSITORY"

      RUNS=$(
        gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/$REPOSITORY/actions/workflows/$WORKFLOW_NAME/runs" \
          --paginate \
          --jq '.workflow_runs[] | select(.conclusion != "") | .id'
      ) 

      echo "Found $(echo "$RUNS" | wc -l) completed runs for workflow $WORKFLOW_NAME"

      for RUN in $RUNS; do
        gh run delete --repo $REPOSITORY $RUN || echo "Failed to delete run $RUN"
        sleep 0.1
      done
    shell: bash