name:  Clean Workflow Runs
author: DevOps
description: Clean Workflow Runs

inputs:
  github-token:
    description: 'GitHub Token (github.token)'
    required: true
  repository:
    description: 'Repository (github.repository)'
    required: true  
  workflow:
    description: 'Workflow file name'
    required: false
    default: ''
  days-ago:
    description: 'Workflow log runs days ago'
    required: false
    default: '0'
  
runs:
  using: 'composite'
  env:
    GH_TOKEN: ${{ inputs.github-token }}
    REPOSITORY: ${{ inputs.repository }}
    WORKFLOW_NAME: ${{ inputs.workflow }}
    DAYS_AGO: ${{ inputs.days-ago }}
  steps:    
  - uses: actions/checkout@v4

  - if: ${{ inputs.workflow == '' }}
    continue-on-error: true
    run: bash ${{ github.action_path }}/expired-runs.sh
    shell: bash

  - if: ${{ inputs.workflow != '' }}
    continue-on-error: true
    run: bash ${{ github.action_path }}/workflow-runs.sh
    shell: bash