name:  Clean Workflow Runs
author: DevOps
description: Clean Workflow Runs

inputs:
  github-token:
    description: 'GitHub Token (github.token)'
    required: true
  repository:
    description: 'Repository (github.repository)'
    required: true  
  workflow:
    description: 'Workflow file name'
    required: false
    default: ''
  days-ago:
    description: 'Workflow log runs days ago'
    required: false
    default: '1'
  test:
    description: 'Not delete, only test'
    required: false
    default: 'false'
  
runs:
  using: 'composite'  
  steps:    
  - uses: actions/checkout@v4

  - env:
      GH_TOKEN: ${{ inputs.github-token }}
      REPOSITORY: ${{ inputs.repository }}
      WORKFLOW_NAME: ${{ inputs.workflow }}
      DAYS_AGO: ${{ inputs.days-ago }}
      TEST: ${{ inputs.test }}
    continue-on-error: true
    run: bash ${{ github.action_path }}/delete-runs.sh
    shell: bash